name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: Build and test with Rake
      run: |
        gem update --system
        bundle install --jobs 4 --retry 3
        bundle exec rspec --format documentation
      env:
        CI: true
        CODECOV_TOKEN: "9bf6770d-10de-4846-be8c-61c479559f34"
